spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://123.206.87.13:3306/newprojbar?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  port: 8081
